-- Tabela Lugar

insert into lugar

(id_Lugar ,N_Lugar,Classe,Comboio_id_Comboio)

values 

(default, '1', '1ªClasse', '1'),
(default, '2', '1ªClasse' ,'1'),
(default, '10', 'Económica','1'),
(default, '11', 'Económica','1'),
(default, '12','Económica','1'),
(default, '13','Económica','1'),
(default, '14','Económica','1'),
(default, '15','Económica','1'),
(default, '16','Económica','1'),
(default, '17','Económica','1'),
(default, '18','Económica','1'),
(default, '19','Económica','1'),
(default, '20','Económica','1'),
(default, '21','Económica','1'),
(default, '22','Económica','1'),
(default, '23','Económica','1'),
(default, '1', '1ªClasse', '2'),
(default, '2', '1ªClasse', '2'),
(default, '3', '1ªClasse', '2'),
(default, '10', 'Económica','2'),
(default, '11','Económica','2'),
(default, '12','Económica','2'),
(default, '13','Económica','2'),
(default, '14','Económica','2'),
(default, '15','Económica','2'),
(default, '16','Económica','2'),
(default, '17','Económica','2'),
(default, '18','Económica','2'),
(default, '19','Económica','2'),
(default, '20','Económica','2'),
(default, '21','Económica','2'),
(default, '22','Económica','2'),
(default, '1', '1ªClasse', '3'),
(default, '10', 'Económica','3'),
(default, '11', 'Económica','3'),
(default, '12', 'Económica','3'),
(default, '13','Económica','3'),
(default, '14','Económica','3'),
(default, '15','Económica','3'),
(default, '16','Económica','3'),
(default, '17','Económica','3'),
(default, '18','Económica','3'),
(default, '19','Económica','3'),
(default, '20','Económica','3'),
(default, '21','Económica','3'),
(default, '22','Económica','3'),
(default, '23','Económica','3'),
(default, '24','Económica','3'),
(default, '1', '1ªClasse','7'),
(default, '2', '1ªClasse','7'),
(default, '3', '1ªClasse','7'),
(default, '4', '1ªClasse','7'),
(default, '5','1ªClasse','7'),
(default, '6','1ªClasse','7'),
(default, '10','Económica','7'),
(default, '11','Económica','7'),
(default, '12','Económica','7'),
(default, '13','Económica','7'),
(default, '14','Económica','7'),
(default, '15','Económica','7'),
(default, '16','Económica','7'),
(default, '17','Económica','7'),
(default, '18','Económica','7'),
(default, '19','Económica','7'),
(default, '1', '1ªClasse', '6'),
(default, '2','1ªClasse' ,'6'),
(default, '3','1ªClasse','6'),
(default, '10','Económica','6'),
(default, '11','Económica','6'),
(default, '12','Económica','6'),
(default, '13','Económica','6'),
(default, '14','Económica','6'),
(default, '15','Económica','6'),
(default, '16','Económica','6'),
(default, '17','Económica','6'),
(default, '18','Económica','6'),
(default, '19','Económica','6'),
(default, '20','Económica','6'),
(default, '21','Económica','6'),
(default, '22','Económica','6'),
(default, '10', 'Económica', '4'),
(default, '11','Económica' ,'4'),
(default, '12','Económica','4'),
(default, '13','Económica','4'),
(default, '14','Económica','4'),
(default, '15','Económica','4'),
(default, '16','Económica','4'),
(default, '17','Económica','4'),
(default, '14','Económica','4'),
(default, '18','Económica','4'),
(default, '19','Económica','4'),
(default, '20','Económica','4'),
(default, '21','Económica','4'),
(default, '22','Económica','4'),
(default, '23','Económica','4'),
(default, '24','Económica','4'),
(default, '1', '1ªClasse', '2'),
(default, '2','1ªClasse' ,'2'),
(default, '10','Económica','2'),
(default, '11','Económica','2'),
(default, '12','Económica','2'),
(default, '13','Económica','2'),
(default, '14','Económica','2'),
(default, '15','Económica','2'),
(default, '16','Económica','2'),
(default, '17','Económica','2'),
(default, '18','Económica','2'),
(default, '19','Económica','2'),
(default, '20','Económica','2'),
(default, '21','Económica','2'),
(default, '22','Económica','2'),
(default, '23','Económica','2'),
(default, '1', '1ªClasse', '4'),
(default, '2','1ªClasse' ,'4'),
(default, '3','1ªClasse','4'),
(default, '4','1ªClasse','4'),
(default, '5','1ªClasse','4'),
(default, '6','1ªClasse','4'),
(default, '7','1ªClasse','4'),
(default, '8','1ªClasse','4'),
(default, '9','1ªClasse','4'),
(default, '10','Económica','4'),
(default, '11','Económica','4'),
(default, '12','Económica','4'),
(default, '13','Económica','4'),
(default, '14','Económica','4'),
(default, '15','Económica','4'),
(default, '16','Económica','4'),
(default, '1', '1ªClasse', '5'),
(default, '2','1ªClasse' ,'5'),
(default, '3','1ªClasse','5'),
(default, '4','1ªClasse','5'),
(default, '10','Económica','5'),
(default, '11','Económica','5'),
(default, '12','Económica','5'),
(default, '13','Económica','5'),
(default, '14','Económica','5'),
(default, '15','Económica','5'),
(default, '16','Económica','5'),
(default, '17','Económica','5'),
(default, '18','Económica','5'),
(default, '19','Económica','5'),
(default, '20','Económica','5'),
(default, '21','Económica','5'),
(default, '1', '1ªClasse', '1'),
(default, '2','1ªClasse' ,'1'),
(default, '3','1ªClasse','1'),
(default, '10','Económica','1'),
(default, '11','Económica','1'),
(default, '12','Económica','1'),
(default, '13','Económica','1'),
(default, '14','Económica','1'),
(default, '15','Económica','1'),
(default, '16','Económica','1'),
(default, '17','Económica','1'),
(default, '18','Económica','1'),
(default, '19','Económica','1'),
(default, '20','Económica','1'),
(default, '21','Económica','1'),
(default, '22','Económica','1'),
(default, '1', '1ªClasse', '7'),
(default, '2','1ªClasse' ,'7'),
(default, '3','1ªClasse','7'),
(default, '4','1ªClasse','7'),
(default, '10','Económica','7'),
(default, '11','Económica','7'),
(default, '12','Económica','7'),
(default, '13','Económica','7'),
(default, '14','Económica','7'),
(default, '15','Económica','7'),
(default, '16','Económica','7'),
(default, '17','Económica','7'),
(default, '18','Económica','7'),
(default, '19','Económica','7'),
(default, '20','Económica','7'),
(default, '21','Económica','7'),
(default, '10','Económica', '2'),
(default, '11','Económica' ,'2'),
(default, '12','Económica','2'),
(default, '13','Económica','2'),
(default, '14','Económica','2'),
(default, '15','Económica','2'),
(default, '16','Económica','2'),
(default, '17','Económica','2'),
(default, '18','Económica','2'),
(default, '19','Económica','2'),
(default, '20','Económica','2'),
(default, '21','Económica','2'),
(default, '22','Económica','2'),
(default, '23','Económica','2'),
(default, '24','Económica','2'),
(default, '25','Económica','2'),
(default, '1','1ªClasse', '6'),
(default, '10','Económica' ,'6'),
(default, '11','Económica','6'),
(default, '12','Económica','6'),
(default, '13','Económica','6'),
(default, '14','Económica','6'),
(default, '15','Económica','6'),
(default, '16','Económica','6'),
(default, '17','Económica','6'),
(default, '18','Económica','6'),
(default, '19','Económica','6'),
(default, '20','Económica','6'),
(default, '21','Económica','6'),
(default, '22','Económica','6'),
(default, '23','Económica','6'),
(default, '24','Económica','6'),
(default, '10','Económica', '3'),
(default, '11','Económica' ,'3'),
(default, '12','Económica','3'),
(default, '13','Económica','3'),
(default, '14','Económica','3'),
(default, '15','Económica','3'),
(default, '16','Económica','3'),
(default, '17','Económica','3'),
(default, '18','Económica','3'),
(default, '19','Económica','3'),
(default, '20','Económica','3'),
(default, '21','Económica','3'),
(default, '22','Económica','3'),
(default, '23','Económica','3'),
(default, '24','Económica','3'),
(default, '25','Económica','3'),
(default, '10', 'Económica', '2'),
(default, '11','Económica' ,'2'),
(default, '12','Económica','2'),
(default, '13','Económica','2'),
(default, '14','Económica','2'),
(default, '15','Económica','2'),
(default, '16','Económica','2'),
(default, '17','Económica','2'),
(default, '18','Económica','2'),
(default, '19','Económica','2'),
(default, '20','Económica','2'),
(default, '21','Económica','2'),
(default, '22','Económica','2'),
(default, '23','Económica','2'),
(default, '24','Económica','2'),
(default, '25','Económica','2'),
(default, '1', '1ªClasse', '5'),
(default, '2','1ªClasse' ,'5'),
(default, '3','1ªClasse','5'),
(default, '4','1ªClasse','5'),
(default, '5','1ªClasse','5'),
(default, '11','Económica','5'),
(default, '12','Económica','5'),
(default, '13','Económica','5'),
(default, '14','Económica','5'),
(default, '15','Económica','5'),
(default, '16','Económica','5'),
(default, '17','Económica','5'),
(default, '18','Económica','5'),
(default, '19','Económica','5'),
(default, '20','Económica','5'),
(default, '21','Económica','5'),
(default, '1', '1ªClasse', '7'),
(default, '2','1ªClasse' ,'7'),
(default, '3','1ªClasse','7'),
(default, '4','1ªClasse','7'),
(default, '5','1ªClasse','7'),
(default, '6','1ªClasse','7'),
(default, '7','1ªClasse','7'),
(default, '8','1ªClasse','7'),
(default, '14','Económica','7'),
(default, '15','Económica','7'),
(default, '16','Económica','7'),
(default, '17','Económica','7'),
(default, '18','Económica','7'),
(default, '19','Económica','7'),
(default, '20','Económica','7'),
(default, '21','Económica','7'),
(default,'1', '1ªClasse','4'),
(default, '10','Económica', '4'),
(default, '11','Económica' ,'4'),
(default, '12','Económica','4'),
(default, '13','Económica','4'),
(default, '14','Económica','4'),
(default, '15','Económica','4'),
(default, '16','Económica','4'),
(default, '17','Económica','4'),
(default, '19','Económica','4'),
(default, '20','Económica','4'),
(default, '21','Económica','4'),
(default, '22','Económica','4'),
(default, '23','Económica','4'),
(default, '24','Económica','4'),
(default, '25','Económica','4'),
(default, '1', '1ªClasse', '5'),
(default, '2','1ªClasse' ,'5'),
(default, '3','1ªClasse','5'),
(default, '4','1ªClasse','5'),
(default, '10','Económica','5'),
(default, '11','Económica','5'),
(default, '12','Económica','5'),
(default, '13','Económica','5'),
(default, '14','Económica','5'),
(default, '15','Económica','5'),
(default, '16','Económica','5'),
(default, '17','Económica','5'),
(default, '18','Económica','5'),
(default, '19','Económica','5'),
(default, '20','Económica','5'),
(default, '21','Económica','5'),
(default, '1', '1ªClasse', '2'),
(default, '2','1ªClasse' ,'2'),
(default, '3','1ªClasse','2'),
(default, '4','1ªClasse','2'),
(default, '5','1ªClasse','2'),
(default, '11','Económica','2'),
(default, '12','Económica','2'),
(default, '13','Económica','2'),
(default, '14','Económica','2'),
(default, '15','Económica','2'),
(default, '16','Económica','2'),
(default, '17','Económica','2'),
(default, '18','Económica','2'),
(default, '19','Económica','2'),
(default, '20','Económica','2'),
(default, '21','Económica','2');