insert into Tipo_Reserva

(id_Tipo_Reserva, Tipo_Quarto, Opcao_Estadia, Reserva_id_Reserva)

values

(default, 'Quarto Duplo Deluxe', '3','1'),
(default, 'Quartos Duplos Superior/Quartos Duplos Superior', '1/1','2'),
(default, 'Quarto Duplo Deluxe', '2','3'),
(default, 'Quarto Individual', '3','4'),
(default, 'Quarto Duplo Superior com Vista/Quarto Duplo Superior com Vista', '2/2','5'),
(default, 'Suite Junior/Suite Junior', '3/3','6'),
(default, 'Suite Executiva/Suite Executiva/Suite Executiva', '3/3/3','7'),
(default, 'Quarto Duplo Deluxe com acesso ao Spa', '1','8'),
(default, 'Suite Familiar', '2','9'),
(default, 'Suite Junior com acesso ao Salão Executivo/Suite Junior com acesso ao Salão Executivo', '1/1','10'),
(default, 'Quarto Duplo ou Twin com Cama Extra', '2','11'),
(default, 'Quarto Duplo', '3','12'),
(default, 'Quarto Triplo Clássico', '2','13'),
(default, 'Apartamento de luxo com Quarto e Vista', '3','14'),
(default, 'Oferta Romântica', '3','15'),
(default, 'Quarto Duplo Superior com Vista/Quarto Duplo Superior com Vista/Quarto Duplo Superior com Vista', '1/1/1','16'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior/Quarto Duplo Superior', '1/1/1','17'),
(default, 'Quarto Duplo ou Twin Deluxe /Quarto Deluxe Premium/Quarto Duplo ou Twin Clube com acesso ao Salão', '2/2/2','18'),
(default, 'Quarto Deluxe com acesso ao Spa e Acesso Wi-Fi Gratuito/Quarto Deluxe com acesso ao Spa e Acesso Wi-Fi Gratuito', '3/3','19'),--
(default, 'Quarto Duplo Superior com Vista Interna/Quarto Duplo Superior com Vista Interna/Quarto Duplo Superior com Vista Interna', '1/1/1','20'),--
(default, 'Suite Presidencial', '3','21'),
(default, 'Quarto Duplo Superior ', '1','22'),
(default, 'Quarto Duplo Deluxe ', '3','23'),
(default, 'Suite Junior/Quarto Duplo Deluxe ', '3/3','24'),
(default, 'Quarto Duplo Deluxe/Suite/Suite', '1/1/1','25'),
(default, 'Plano Familiar', '2','26'),
(default, 'Suite Junior Premium/Suite Junior Premium', '3/2','27'),
(default, 'Quarto Duplo Deluxe/Quarto Duplo Deluxe/Quarto Duplo Deluxe', '3/2/1','28'),
(default, 'Suite/Suite/Plano Familiar/Plano Familiar', '3/3/2/1','29'),
(default, 'Suite', '3','30'),
(default, 'Suite', '3','31'),
(default, 'Quarto Duplo Deluxe/Quarto Duplo Deluxe', '2/1','32'),
(default, 'Suite Júnior Premier/Suite Júnior Premier', '3/2','33'),
(default, 'Quarto Duplo Deluxe/Suite Júnior/Suite Júnior', '3/1/2','34'),
(default, 'Suite Júnior Premier/Suite/Suite/Suite', '1/1/1/1','35'),
(default, 'Quarto Duplo Deluxe', '1','36'),
(default, 'Plano Familiar', '3','37'),
(default, 'Suite Junior', '2','38'),
(default, 'Suite Junior Premier', '1','39'),
(default, 'Suite', '1','40'),
(default, 'Suite/Suite', '2/2','41'),
(default, 'Plano Familiar/Plano Familiar', '1/3','42'),
(default, 'Oferta Romântica', '3','43'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior', '3/2','44'),
(default, 'Quarto Duplo Superior/Quarto Individual/Quarto Individual', '1/1/1','45'),
(default, 'Quarto Duplo ou Twin com Cama Extra', '3','46'),
(default, 'Quarto Individual/Quarto Individual', '3/3','47'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior/Quarto Duplo Superior', '3/2/1','48'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior/Quarto Duplo Superior/Quarto Duplo Superior', '3/3/2/1','49'),
(default, 'Quarto Individual', '2','50'),
(default, 'Quarto Duplo ou Twin com Cama Extra', '1','51'),
(default, 'Quarto Individual/Quarto Individual', '3/3','52'),
(default, 'Quarto Duplo Superior/Quarto Duplo ou Twin com Cama Extra', '3/3','53'),
(default, 'Oferta Romântica/Quarto Duplo Superior/Quarto Duplo Superior', '1/1/1','54'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior/Quarto Duplo Superior/Quarto Duplo Superior', '3/3/3/3','55'),
(default, 'Oferta Romântica', '2','56'),
(default, 'Oferta Romântica', '2','57'),
(default, 'Quarto Duplo ou Twin com Cama Extra', '2','58'),
(default, 'Quarto Individual', '3','59'),
(default, 'Quarto Individual', '3','60'),
(default, 'Quarto Duplo ou Twin com Cama Extra/Quarto Duplo ou Twin com Cama Extra', '3/2','61'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior', '3/3','62'),
(default, 'Quarto Duplo Superior - com vista', '2','63'),
(default, 'Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista', '2/2','64'),
(default, 'Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista', '3/3','65'),
(default, 'Quarto Duplo Superior - com vista', '1','66'),
(default, 'Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista', '3/2','67'),
(default, 'Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista', '3/3/3','68'),
(default, 'Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista', '3/3/3','69'),
(default, 'Quarto Duplo Superior - com vista', '1','70'),
(default, 'Quarto Duplo Superior - com vista', '1','71'),
(default, 'Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista', '2/1','72'),
(default, 'Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista', '1/1','73'),
(default, 'Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista', '1/1/1','74'),
(default, 'Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista', '2/2','75'),
(default, 'Quarto Duplo Superior - com vista', '3','76'),
(default, 'Quarto Duplo Superior - com vista', '3','77'),
(default, 'Quarto Duplo Superior - com vista', '2','78'),
(default, 'Quarto Duplo Superior - com vista', '2','79'),
(default, 'Quarto Duplo Superior - com vista', '1','80'),
(default, 'Quarto Duplo Superior - com vista/Quarto Duplo Superior - com vista', '2/3','81'),
(default, 'Quarto Duplo Superior - com vista', '3','82'),
(default, 'Suite Júnior', '2','83'),
(default, 'Suite Júnior/Suite Junior', '2/2','84'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior','3/2','85'),
(default, 'Quarto Duplo ou Twin Standard','3','86'),
(default, 'Quarto Duplo ou Twin Executivo/Quarto Duplo ou Twin Executivo','3/1','87'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior/Quarto Duplo Superior','3/2/1','88'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior/Quarto Duplo Superior','3/2/1','89'),
(default, 'Suite Júnior', '2','90'),
(default, 'Suite Júnior', '1','91'),
(default, 'Quarto Duplo ou Twin Executivo/Quarto Duplo ou Twin Executivo','3/3','92'),
(default, 'Suite Júnior/Suite Junior', '1/1','93'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior/Quarto Duplo Superior','3/3/3','94'),
(default, 'Quarto Duplo ou Twin Executivo/Quarto Duplo ou Twin Executivo','2/2','95'),
(default, 'Quarto Duplo ou Twin Standard','3','96'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior','3/3','97'),
(default, 'Suite Júnior', '1','98'),
(default, 'Quarto Duplo ou Twin Standard','1','99'),
(default, 'Quarto Duplo ou Twin Standard','1','100'),
(default, 'Suite Júnior/Suite Junior', '3/3','101'),
(default, 'Quarto Duplo ou Twin Executivo', '3','102'),
(default, 'Suite Executiva', '3','103'),
(default, 'Suite Executiva/Suite Executiva', '3/3','104'),
(default, 'Suite Executiva/Suite Executiva', '1/1','105'),
(default, 'Quarto Duplo ou Twin Clube com acesso ao Salão', '3','106'),
(default, 'Quarto Deluxe Premium/Quarto Deluxe Premium', '3/3','107'),
(default, 'Quarto Duplo ou Twin Deluxe/Quarto Duplo ou Twin Deluxe/Quarto Duplo ou Twin Deluxe', '3/3/3','108'),
(default, 'Quarto Duplo ou Twin Clube com acesso ao Salão/Quarto Duplo ou Twin Clube com acesso ao Salão/Quarto Duplo ou Twin Clube com acesso ao Salão', '3/3/3','109'),
(default, 'Suite Junior', '3','110'),
(default, 'Quarto Deluxe Premium', '1','111'),
(default, 'Suite Junior/Suite Junior', '3/2','112'),
(default, 'Quarto Deluxe Premium/Quarto Deluxe Premium', '1/2','113'),
(default, 'Quarto Duplo ou Twin Deluxe/Quarto Duplo ou Twin Deluxe/Quarto Deluxe Premium', '2/3/1','114'),
(default, 'Suite Executiva/Suite Executiva','1/2','115'),
(default, 'Quarto Duplo ou Twin Deluxe', '3','116'),
(default, 'Suite Executiva/Suite Executiva', '1/2','117'),
(default, 'Suite Junior', '2','118'),
(default, 'Suite Junior', '2','119'),
(default, 'Suite Executiva', '3','120'),
(default, 'Suite Executiva/Suite Executiva', '3/3','121'),
(default, 'Suite Executiva', '3','122'),
(default, 'Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito', '1','123'),
(default, 'Suite Grand Premier com Acesso ao Spa & Vale de Oferta/Suite Grand Premier com Acesso ao Spa & Vale de Oferta', '3/3','124'),
(default, 'Quarto Duplo Superior com Acesso ao Spa e Acesso Wi-Fi Gratuito/Quarto Duplo Superior com Acesso ao Spa e Acesso Wi-Fi Gratuito', '1/2','125'),
(default, 'Suite Grand Premier com Acesso ao Spa & Vale de Oferta', '3','126'),
(default, 'Suite Familiar (2 Adultos + 2 Crianças) com Acesso ao Spa e Vale Oferta/Suite Familiar (2 Adultos + 2 Crianças) com Acesso ao Spa e Vale Oferta', '3/3','127'),
(default, 'Suite Familiar (2 Adultos + 2 Crianças) com Acesso ao Spa e Vale Oferta/Suite Familiar (2 Adultos + 2 Crianças) com Acesso ao Spa e Vale Oferta/Suite Grand Premier com Acesso ao Spa & Vale de Oferta', '2/2/3','128'),
(default, 'Suite Familiar (2 Adultos + 2 Crianças) com Acesso ao Spa e Vale Oferta/Suite Familiar (2 Adultos + 2 Crianças) com Acesso ao Spa e Vale Oferta/Suite Grand Premier com Acesso ao Spa & Vale de Oferta', '2/2/3','129'),
(default, 'Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito', '2','130'),
(default, 'Suite Familiar (2 Adultos + 2 Crianças) com Acesso ao Spa e Vale Oferta', '1','131'),
(default, 'Suite Grand Premier com Acesso ao Spa & Vale de Oferta/Suite Grand Premier com Acesso ao Spa & Vale de Oferta', '3/3','132'),
(default, 'Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito/Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito', '2/2','133'),
(default, 'Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito/Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito/Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito', '1/2/3','134'),
(default, 'Suite Grand Premier com Acesso ao Spa & Vale de Oferta', '1','135'),
(default, 'Suite Grand Premier com Acesso ao Spa & Vale de Oferta/Suite Grand Premier com Acesso ao Spa & Vale de Oferta', '2/3','136'),
(default, 'Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito', '1','137'),
(default, 'Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito', '1','138'),
(default, 'Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito', '1','139'),
(default, 'Quarto Duplo Deluxe com Acesso ao Spa e Acesso Wi-Fi Gratuito', '1','140'),
(default, 'Quarto Duplo Superior com Vista Interna', '2','141'),
(default, 'Quarto Twin Superior com Vista Interior/Suite Familiar - 1 quarto/Suite Familiar - 1 quarto', '3/1/3','142'),
(default, 'Suite Familiar - 1 quarto/Quarto Duplo Superior com Vista Interna', '1/2','143'),
(default, 'Quarto Duplo Superior com Vista Interna/Quarto Duplo Superior com Vista Interna/Quarto Duplo Superior com Vista Interna', '2/2/2','144'),
(default, 'Quarto Duplo Superior com Vista Interna', '3','145'),
(default, 'Suite Familiar - 1 quarto', '2','146'),
(default, 'Suite Familiar - 1 quarto/Suite Familiar - 1 quarto', '3/3','147'),
(default, 'Quarto Duplo Superior com Vista Interna/Suite Familiar - 1 quarto/Suite Familiar - 1 quarto', '3/1/2','148'),
(default, 'Suite Familiar - 1 quarto', '1','149'),
(default, 'Quarto Twin Superior com Vista Interior/Quarto Twin Superior com Vista Interior', '2/2','150'),
(default, 'Quarto Duplo Superior com Vista Interna', '1','151'),
(default, 'Quarto Twin Superior com Vista Interior/Quarto Twin Superior com Vista Interior', '3/3','152'),
(default, 'Quarto Duplo Superior com Vista Interna/Quarto Twin Superior com Vista Interior', '2/1','153'),
(default, 'Quarto Twin Superior com Vista Interior/Quarto Twin Superior com Vista Interior/Quarto Twin Superior com Vista Interior', '1/2/2','154'),
(default, 'Suite Familiar - 1 quarto/Quarto Twin Superior com Vista Interior', '3/1','155'),
(default, 'Quarto Duplo Superior com Vista Interna/Quarto Twin Superior com Vista Interior/Suite Familiar - 1 quarto', '1/2/3','156'),
(default, 'Quarto Twin Superior com Vista Interior/Suite Familiar - 1 quarto/Suite Familiar - 1 quarto/Quarto Duplo Superior com Vista Interna/Suite Familiar', '3/3/1/2','157'),
(default, 'Quarto Duplo Superior com Vista Interna/Suite Familiar - 1 quarto', '1/1','158'),
(default, 'Quarto Duplo Superior com Vista Interna', '3','159'),
(default, 'Suite Familiar - 1 quarto', '2','160'),
(default, 'Suite Júnior com Acesso ao Salão Executivo', '2','161'),
(default, 'Quarto Duplo Executivo com Acesso ao Salão', '3','162'),
(default, 'Suite Júnior com Acesso ao Salão Executivo/Suite Presidencial', '1/3','163'),
(default, 'Quarto Duplo Executivo com Acesso ao Salão/Suite Júnior com Acesso ao Salão Executivo/Suite Presidencial', '3/2/3','164'),
(default, 'Suite Júnior com Acesso ao Salão Executivo/Suite Júnior com Acesso ao Salão Executivo', '1/1','165'),
(default, 'Suite Presidencial/Suite Júnior com Acesso ao Salão Executivo', '3/2','166'),
(default, 'Quarto Duplo Executivo com Acesso ao Salão', '2','167'),
(default, 'Suite Presidencial', '3','168'),
(default, 'Suite Júnior com Acesso ao Salão Executivo/Suite Presidencial/Quarto Duplo Executivo com Acesso ao Salão', '2/1/3','169'),
(default, 'Suite Presidencial/Suite Presidencial', '2/2','170'),
(default, 'Quarto Duplo Executivo com Acesso ao Salão', '3','171'),
(default, 'Suite Presidencial/Suite Júnior com Acesso ao Salão Executivo', '1/1','172'),
(default, 'Suite Júnior com Acesso ao Salão Executivo/Suite Presidencial/Quarto Duplo Executivo com Acesso ao Salão/Suite Presidencial', '1/3/2/3','173'),
(default, 'Suite Presidencial', '2','174'),
(default, 'Suite Júnior com Acesso ao Salão Executivo/Suite Presidencial', '1/2','175'),
(default, 'Suite Presidencial/Quarto Duplo Executivo com Acesso ao Salão/Suite Presidencial', '3/3/1','176'),
(default, 'Suite Presidencial/Suite Júnior com Acesso ao Salão Executivo', '2/2','177'),
(default, 'Quarto Duplo Executivo com Acesso ao Salão/Suite Júnior com Acesso ao Salão Executivo', '1/3','178'),
(default, 'Suite Presidencial', '2','179'),
(default, 'Quarto Duplo Executivo com Acesso ao Salão', '3','180'),
(default, 'Quarto Duplo ou Twin com Cama Extra (3 Adultos)', '3','181'),
(default, 'Quarto Duplo ou Twin com Terraço/Quarto Duplo Superior', '2/1','182'),
(default, 'Quarto Duplo Superior', '3','183'),
(default, 'Quarto Duplo ou Twin com Terraço/Quarto Duplo Superior/Quarto Duplo ou Twin com Cama Extra (3 Adultos)', '3/1/3','184'),
(default, 'Quarto Duplo Superior', '2','185'),
(default, 'Quarto Duplo ou Twin com Cama Extra (3 Adultos)', '1','186'),
(default, 'Quarto Duplo Superior/Quarto Duplo Superior', '3/3','187'),
(default, 'Quarto Duplo Superior/Quarto Duplo ou Twin com Terraço/Quarto Duplo Superior', '1/2/3','188'),
(default, 'Quarto Duplo ou Twin com Cama Extra (3 Adultos)/Quarto Duplo ou Twin com Cama Extra (3 Adultos)/Quarto Duplo Superior', '1/1/3','189'),
(default, 'Quarto Duplo ou Twin com Terraço/Quarto Duplo Superior', '2/1','190'),
(default, 'Quarto Duplo Superior/Quarto Duplo ou Twin com Terraço/Quarto Duplo ou Twin com Cama Extra (3 Adultos)', '3/1/2','191'),
(default, 'Quarto Duplo ou Twin com Terraço', '3','192'),
(default, 'Quarto Duplo ou Twin com Terraço', '2','193'),
(default, 'Quarto Duplo ou Twin com Terraço/Quarto Duplo Superior', '2/1','194'),
(default, 'Quarto Duplo Superior', '2','195'),
(default, 'Quarto Duplo ou Twin com Terraço/Quarto Duplo Superior/Quarto Duplo ou Twin com Terraço/Quarto Duplo Superior', '2/3/1/3','196'),
(default, 'Quarto Duplo ou Twin com Terraço/Quarto Duplo ou Twin com Cama Extra (3 Adultos)', '3/1','197'),
(default, 'Quarto Duplo ou Twin com Terraço/Quarto Duplo ou Twin com Cama Extra (3 Adultos)/Quarto Duplo Superior', '2/2/3','198'),
(default, 'Quarto Duplo ou Twin com Cama Extra (3 Adultos)', '2','199'),
(default, 'Quarto Duplo Superior', '3','200'),
(default, 'Quarto Duplo', '3','201'),
(default, 'Quarto Duplo/Quarto Duplo', '2/2','202'),
(default, 'Quarto Twin/Quarto Twin', '1/1','203'),
(default, 'Quarto Duplo', '2','204'),
(default, 'Quarto Duplo/Quarto Twin', '3/2','205'),
(default, 'Quarto Duplo/Quarto Duplo/Quarto Duplo', '3/2/1','206'),
(default, 'Quarto Twin/Quarto Twin/Quarto Twin', '1/1/1','207'),
(default, 'Quarto Twin', '2','208'),
(default, 'Quarto Twin', '1','209'),
(default, 'Quarto Twin/Quarto Twin', '1/1','210'),
(default, 'Quarto Twin/Quarto Twin', '2/2','211'),
(default, 'Quarto Duplo/Quarto Duplo/Quarto Duplo', '3/3/3','212'),
(default, 'Quarto Duplo/Quarto Duplo', '3/3','213'),
(default, 'Quarto Duplo', '1','214'),
(default, 'Quarto Twin/Quarto Twin', '2/3','215'),
(default, 'Quarto Twin', '2','216'),
(default, 'Quarto Twin', '3','217'),
(default, 'Quarto Twin', '2','218'),
(default, 'Quarto Twin/Quarto Twin', '3/2','219'),
(default, 'Quarto Twin/Quarto Duplo', '3/1','220'),
(default, 'Quarto Duplo ou Twin Económico - Sótão', '2','221'),
(default, 'Quarto Duplo ou Twin Económico - Sótão/Quarto Duplo ou Twin Económico - Sótão', '2/2','222'),
(default, 'Quarto Triplo Clássico/Quarto Duplo Deluxe', '3/2','223'),
(default, 'Quarto Triplo Clássico', '1','224'),
(default, 'Quarto Duplo ou Twin Económico - Sótão/Quarto Duplo ou Twin Económico - Sótão', '3/2','225'),
(default, 'Quarto Duplo Deluxe/Quarto Duplo Deluxe/Quarto Duplo Deluxe', '3/2/1','226'),
(default, 'Quarto Triplo Clássico/Quarto Triplo Clássico/Quarto Triplo Clássico', '1/2/3','227'),
(default, 'Quarto Duplo Deluxe', '2','228'),
(default, 'Quarto Duplo Deluxe', '1','229'),
(default, 'Quarto Duplo ou Twin Económico - Sótão/Quarto Duplo ou Twin Económico - Sótão', '2/1','230'),
(default, 'Quarto Duplo Deluxe/Quarto Triplo Clássico', '1/1','231'),
(default, 'Quarto Duplo Deluxe/Quarto Duplo Deluxe/Quarto Duplo Deluxe', '3/3/3','232'),
(default, 'Quarto Duplo ou Twin Económico - Sótão/Quarto Duplo ou Twin Económico - Sótão', '2/2','233'),
(default, 'Quarto Duplo ou Twin Económico - Sótão', '2','234'),
(default, 'Quarto Triplo Clássico/Quarto Triplo Clássico', '2/3','235'),
(default, 'Quarto Duplo ou Twin Económico - Sótão', '3','236'),
(default, 'Quarto Duplo ou Twin Económico - Sótão', '3','237'),
(default, 'Quarto Duplo ou Twin Económico - Sótão', '3','238'),
(default, 'Quarto Triplo Clássico/Quarto Triplo Clássico', '3/2','239'),
(default, 'Quarto Triplo Clássico', '1','240'),
(default, 'Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores', '3','241'),
(default, 'Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores/Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores', '3/3','242'),
(default, 'Apartamento de Luxo com 1 Quarto e Vista - Não Fumadores/Apartamento de Luxo com 1 Quarto e Vista - Não Fumadores', '3/2','243'),
(default, 'Apartamento Executivo com 1 Quarto - Não Fumadores', '1','244'),
(default, 'Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores/Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores', '3/3','245'),
(default, 'Apartamento Executivo com 1 Quarto - Não Fumadores/Apartamento Executivo com 1 Quarto - Não Fumadores/Apartamento Executivo com 1 Quarto - Não Fumadores', '2/2/2','246'),
(default, 'Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores/Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores/Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores', '3/2/1','247'),
(default, 'Apartamento de Luxo com 1 Quarto e Vista - Não Fumadores', '3','248'),
(default, 'Apartamento Executivo com 1 Quarto - Não Fumadores', '1','249'),
(default, 'Apartamento Executivo com 1 Quarto - Não Fumadores/Apartamento Executivo com 1 Quarto - Não Fumadores', '2/1','250'),
(default, 'Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores/Apartamento de Luxo com 1 Quarto e Vista - Não Fumadores', '1/3','251'),
(default, 'Apartamento de Luxo com 1 Quarto e Vista - Não Fumadores/Apartamento de Luxo com 1 Quarto e Vista - Não Fumadores/Apartamento de Luxo com 1 Quarto e Vista - Não Fumadores', '3/3/3','252'),
(default, 'Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores/Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores', '2/2','253'),
(default, 'Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores', '2','254'),
(default, 'Apartamento Executivo com 1 Quarto - Não Fumadores/Apartamento Executivo com 1 Quarto - Não Fumadores', '1/1','255'),
(default, 'Apartamento Executivo com 1 Quarto - Não Fumadores', '1','256'),
(default, 'Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores', '1','257'),
(default, 'Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores', '1','258'),
(default, 'Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores/Apartamento Deluxe com 1 Quarto e Vista - Não Fumadores', '3/1','259'),
(default, 'Apartamento de Luxo com 1 Quarto e Vista - Não Fumadores', '1','260'); 



